name: Bivio Photo
favicon: null
layout_spectrum: 0.5933136080857366
typography_spectrum: 0.42544437455944717
title: Bivio Photo
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.671497791307047
  lightness: 0.14538809610530734
  saturation: 0.48967331694439054
  rhythmicContrast: 0.7864900885615498
purpose: []
