name: Bivio Photo
favicon: null
layout_spectrum: 0.48802
typography_spectrum: 0.42544437455944717
title: Bivio Photo
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0a0a'
    - '#fefefe'
    - '#3d3d3d'
    - '#a77f80'
    - '#adadad'
  brandStrength: 0.5
  lightness: 0.14538809610530734
  saturation: 0.48967331694439054
  rhythmicContrast: 0.7864900885615498
purpose: []
